In [2]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 747.8 kB/s eta 0:00:00a 0:00:01
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [116]:
from pymongo import MongoClient
import pandas as pd
import re

In [117]:
client = MongoClient("mongodb://admin:admin@mongodb:27017")
db = client["sample_mflix"]

### users

In [118]:
docs_users = list(db['users'].find())
users = pd.DataFrame(docs_users)
users = users.drop('preferences', axis = 1)

In [119]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   _id       185 non-null    object
 1   name      185 non-null    object
 2   email     185 non-null    object
 3   password  185 non-null    object
dtypes: object(4)
memory usage: 5.9+ KB

In [120]:
users

,_id,name,email,password
0,59b99db4cfa9a34dcd7885b6,Ned Stark,sean_bean@gameofthron.es,$2b$12$UREFwsRUoyF0CRqGNK0LzO0HM/jLhgUCNNIJ9RJ...
1,59b99db4cfa9a34dcd7885b7,Robert Baratheon,mark_addy@gameofthron.es,$2b$12$yGqxLG9LZpXA2xVDhuPnSOZd.VURVkz7wgOLY3p...
2,59b99db5cfa9a34dcd7885b8,Jaime Lannister,nikolaj_coster-waldau@gameofthron.es,$2b$12$6vz7wiwO.EI5Rilvq1zUc./9480gb1uPtXcahDx...
3,59b99db5cfa9a34dcd7885b9,Catelyn Stark,michelle_fairley@gameofthron.es,$2b$12$fiaTH5Sh1zKNFX2i/FTEreWGjxoJxvmV7XL.qlf...
4,59b99db6cfa9a34dcd7885ba,Cersei Lannister,lena_headey@gameofthron.es,$2b$12$FExjgr7CLhNCa.oUsB9seub8mqcHzkJCFZ8heMc...
...,...,...,...,...
180,59b99e08cfa9a34dcd78866a,Shawn Mccormick,shawn_mccormick@fakegmail.com,$2b$12$fVJEFj7SXlqT0EmE9k00FuZLNH52NFSPriUqm8G...
181,59b99e09cfa9a34dcd78866b,Anthony Hurst,anthony_hurst@fakegmail.com,$2b$12$9M2cew6pOM.35LY474rMkeVD4WxfvF2lDtVg60j...
182,59b99e09cfa9a34dcd78866c,Ashlee Hart,ashlee_hart@fakegmail.com,$2b$12$S707opDk6HG/Lqk7MaHeQ.1N36I6kEUOhRv/RQE...
183,5db1c37e4a68c31f10cf0a98,Magical Mr. Mistoffelees,magicz@cats.com,somehashedpw
184,5db1c37e4a68c31f10cf0a9f,foo,foobaz@bar.com,foobar

### comments

In [121]:
docs_comments = list(db['comments'].find())
comments = pd.DataFrame(docs_comments)

In [122]:
comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41079 entries, 0 to 41078
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   _id       41079 non-null  object
 1   name      41079 non-null  object
 2   email     41079 non-null  object
 3   movie_id  41079 non-null  object
 4   text      41079 non-null  object
 5   date      41079 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.9+ MB

In [123]:
comments

,_id,name,email,movie_id,text,date
0,5a9427648b0beebeb69579e7,Mercedes Tyler,mercedes_tyler@fakegmail.com,573a1390f29313caabcd4323,Eius veritatis vero facilis quaerat fuga tempo...,2002-08-18 04:56:07
1,5a9427648b0beebeb69579f5,John Bishop,john_bishop@fakegmail.com,573a1390f29313caabcd446f,Id error ab at molestias dolorum incidunt. Non...,1975-01-21 00:31:22
2,5a9427648b0beebeb6957a21,Jaqen H'ghar,tom_wlaschiha@gameofthron.es,573a1390f29313caabcd516c,Minima odit officiis minima nam. Aspernatur id...,1981-11-08 04:32:25
3,5a9427648b0beebeb6957a22,Taylor Scott,taylor_scott@fakegmail.com,573a1390f29313caabcd4eaf,Iure laboriosam quo et necessitatibus sed. Id ...,1970-11-15 05:54:02
4,5a9427648b0beebeb6957a38,Yara Greyjoy,gemma_whelan@gameofthron.es,573a1390f29313caabcd587d,Nobis incidunt ea tempore cupiditate sint. Ita...,2012-11-26 11:00:57
...,...,...,...,...,...,...
41074,5a9427658b0beebeb697c337,Roose Bolton,michael_mcelhatton@gameofthron.es,573a13faf29313caabdec056,Id quod quisquam vitae natus facere qui numqua...,2001-10-25 22:00:54
41075,5a9427658b0beebeb697c339,Gilly,hannah_murray@gameofthron.es,573a13faf29313caabdec1f8,Hic magni ad maiores quo eligendi expedita bea...,1978-09-02 18:14:28
41076,5a9427658b0beebeb697c36e,Thoros of Myr,paul_kaye@gameofthron.es,573a13faf29313caabdeca48,Quia sint reiciendis ea aspernatur animi optio...,1989-02-25 14:30:05
41077,5a9427658b0beebeb697c37a,Teresa Thomas,teresa_thomas@fakegmail.com,573a13faf29313caabdecaf3,Fugit delectus iusto nisi aspernatur eos sapie...,1993-11-09 16:14:37
41078,5a9427658b0beebeb697c39c,Melissa Jones,melissa_jones@fakegmail.com,573a13faf29313caabded1d6,Expedita distinctio minima ullam iste. Ea inve...,1990-02-21 11:27:31

### movies

In [131]:
docs_movies = list(db['movies'].find())
movies = pd.json_normalize(docs_movies, sep = '_')
movies = movies[["_id", "title", "year", "released", 
                 "runtime", "genres", "countries", 
                 "languages", "imdb_rating", "imdb_votes", 
                 "tomatoes_viewer_rating", "tomatoes_viewer_numReviews", "num_mflix_comments"]]

movies["year"] = movies["year"].astype(str)
movies["year"] = movies["year"].apply(lambda x: x.replace('è','') if not re.search(r'\d{4}.\d{4}', x) else x.replace('è','-'))
movies['imdb_rating'] = pd.to_numeric(movies['imdb_rating'])
movies['imdb_votes'] = pd.to_numeric(movies['imdb_votes']).astype("Int64")
movies['tomatoes_viewer_numReviews'] = pd.to_numeric(movies['tomatoes_viewer_numReviews']).astype("Int64")

In [141]:
pd.json_normalize(docs_movies).columns

Index(['_id', 'plot', 'genres', 'runtime', 'cast', 'poster', 'title',
       'fullplot', 'languages', 'released', 'directors', 'rated',
       'lastupdated', 'year', 'countries', 'type', 'num_mflix_comments',
       'awards.wins', 'awards.nominations', 'awards.text', 'imdb.rating',
       'imdb.votes', 'imdb.id', 'tomatoes.viewer.rating',
       'tomatoes.viewer.numReviews', 'tomatoes.viewer.meter', 'tomatoes.fresh',
       'tomatoes.critic.rating', 'tomatoes.critic.numReviews',
       'tomatoes.critic.meter', 'tomatoes.rotten', 'tomatoes.lastUpdated',
       'writers', 'tomatoes.dvd', 'tomatoes.website', 'tomatoes.production',
       'tomatoes.consensus', 'metacritic', 'tomatoes.boxOffice'],
      dtype='object')

In [132]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21349 entries, 0 to 21348
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   _id                         21349 non-null  object
 1   title                       21349 non-null  object
 2   year                        21349 non-null  object
 3   released                    20878 non-null  datetime64[ns]
 4   runtime                     20910 non-null  float64
 5   genres                      21237 non-null  object
 6   countries                   21339 non-null  object
 7   languages                   21119 non-null  object
 8   imdb_rating                 21288 non-null  float64
 9   imdb_votes                  21287 non-null  Int64
 10  tomatoes_viewer_rating      18566 non-null  float64
 11  tomatoes_viewer_numReviews  18583 non-null  Int64
 12  num_mflix_comments          21349 non-null  int64
dtypes: Int64(2), datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 2.2+ MB

In [130]:
movies

,_id,title,year,released,runtime,genres,countries,languages,imdb_rating,imdb_votes,tomatoes_viewer_rating,tomatoes_viewer_numReviews,num_mflix_comments
0,573a1390f29313caabcd42e8,The Great Train Robbery,1903,1903-12-01,11.0,"[Short, Western]",[USA],[English],7.4,9847,3.7,2559.0,0
1,573a1390f29313caabcd446f,A Corner in Wheat,1909,1909-12-13,14.0,"[Short, Drama]",[USA],[English],6.6,1375,3.6,109.0,1
2,573a1390f29313caabcd4803,"Winsor McCay, the Famous Cartoonist of the N.Y...",1911,1911-04-08,7.0,"[Animation, Short, Comedy]",[USA],[English],7.3,1034,3.4,89.0,0
3,573a1390f29313caabcd4eaf,Traffic in Souls,1913,1913-11-24,88.0,"[Crime, Drama]",[USA],[English],6.0,371,3.0,85.0,1
4,573a1390f29313caabcd50e5,Gertie the Dinosaur,1914,1914-09-15,12.0,"[Animation, Short, Comedy]",[USA],[English],7.3,1837,3.7,29.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21344,573a13faf29313caabded1d6,The Laundryman,2015,2015-07-11,110.0,[Comedy],[Taiwan],[Mandarin],6.3,27,NaN,NaN,1
21345,573a13faf29313caabded406,The Red Spider,2015,2015-11-20,90.0,[Thriller],"[Poland, Czech Republic, Slovakia]","[Polish, English]",7.4,16,NaN,NaN,0
21346,573a13fbf29313caabdedf30,Our Loved Ones,2015,2015-08-12,102.0,[Drama],[Canada],[French],7.4,5,NaN,NaN,0
21347,573a13fbf29313caabdedf31,No Home Movie,2015,2015-08-10,115.0,[Documentary],"[Belgium, France]",[French],3.8,5,NaN,NaN,0
21348,573a13fbf29313caabdee03b,Scenes of a Sexual Nature,2006,NaT,91.0,"[Comedy, Drama, Romance]",[UK],[English],6.1,4125,3.1,4807.0,0

### theaters

In [114]:
docs_theaters = list(db['theaters'].find())
theaters = pd.json_normalize(docs_theaters, sep = '_')

In [ ]:
theaters

In [133]:
theaters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1564 entries, 0 to 1563
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _id                       1564 non-null   object
 1   theaterId                 1564 non-null   int64
 2   location_address_street1  1564 non-null   object
 3   location_address_city     1564 non-null   object
 4   location_address_state    1564 non-null   object
 5   location_address_zipcode  1564 non-null   object
 6   location_geo_type         1564 non-null   object
 7   location_geo_coordinates  1564 non-null   object
 8   location_address_street2  367 non-null    object
dtypes: int64(1), object(8)
memory usage: 110.1+ KB